### ISSUE TITLE
PlatformException(IO_ERROR, A network error occurred trying to lookup the supplied coordinates

### ISSUE THREAD

**Issue by dev-abdullah-github** [Baseflow/flutter-geocoding#9] opened 2020-09-12 19:48 UTC
### Old (and correct) behavior

PlatformException(IO_ERROR, A network error occurred trying to lookup the supplied coordinates

### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment] 2020-09-14 09:26
@dev-abdullah-github you will receive this error when the geocoding SDK of the platfrom (CLGeocoder on iOS or Geocoder on Android) cannot connect to their backend services. 

Both Android and iOS rely on submitting the coordinates to their servers to do the translation. This error is thrown in the following situations:

- The device doesn't have a internet connection;
- The backend services are down (we have seen this happen on Apple).

Next time please fill in the complete template so I can provide better support. I will close this issue now since this is not an error related to the geocoding plugin but to the Android / iOS services.

**Closed by mvanbeusekom** 2020-09-14 09:26 UTC

**Comment by CoderJava** [comment] 2020-12-21 12:41
I have the same issue. But I don't know how to reproduce this error.

**Comment by rhernandez-itemsoft** [comment] 2021-08-07 22:57
pff, I have internet and I use "geolocation and google_maps_flutter plugins" correctly but "geocoding plugin" not work
nhandled Exception: PlatformException(IO_ERROR, A network error occurred trying to lookup the supplied coordinates (latitude...

**Comment by pishguy** [comment] 2021-08-18 07:00
@mvanbeusekom 

+1

i have the same problem, i'm testing on real device 

internet connection is on
location is on
permission granted 
minSdk is 19

**Comment by mvanbeusekom** [comment] 2021-08-23 15:51
Hi @rhernandez-itemsoft, @pishguy, 

More detailed investigation revealed this issue is caused by the rate limitations related to the free services provided by Apple and Google (see README and also issues #9, #12, #23, #28, 35# and #49 for more detailed information).

**Comment by mabbasi17** [comment] 2022-01-04 00:59
> 

minSdk was 16 , turned to 21 and it worked like magic

**Comment by cedvdb** [comment] 2022-04-15 14:20
A RateLimitedException would be nice
