### ISSUE TITLE
Get a network exception calling function locationFromAddress()

### ISSUE THREAD

**Issue by aden-collector** [Baseflow/flutter-geocoding#84] opened 2022-02-02 18:49 UTC
I call the function locationFromAddress(city,state) to get the coordinates of a city/state for google place search.  When I call this function for chicago, il I get a "a network error occurred trying to look up the address".  The runtime type is a platform exception.

I'm using the latest version of geocoding.  

Phone details I'm running the app on:

motorola one 5g ace
Android version 10

I made the following changes in the gradle files:

gradle.properties file
----------------------
android.useAndroidX=true
android.enableJetifier=true

gradle build file
------------------
android {
 compileSdkVersion 30
}

When I run the same app on a moto G 5s Plus Phone running Android 8.10, I don't get any exception.  The function call returns the coordinates of Chicago IL using chicago, il for the input.

**Comment by aden-collector** [comment] 2022-02-11 16:20
The reason the geocode function call is failing is that geocoding needs to be added to added to your API Key on the google developers console.

**Comment by mvanbeusekom** [comment] 2022-03-09 09:03
This issue is  caused by the rate limitations related to the free services provided by Android (see README and also issues #9, #12, #23, #28, 35# and #49).

I will be closing this issue now as there is nothing I can do about this error. You are simply hitting the limitations of the free services provided by Google and Apple.

**Closed by mvanbeusekom** 2022-03-09 09:03 UTC
