### ISSUE TITLE
PlatformException(IO_ERROR, A network error occurred trying to lookup the supplied coordinates

### ISSUE THREAD

**Issue by Prabhu-Ramesh** [Baseflow/flutter-geocoding#35] opened 2021-02-05 06:10 UTC
## 🐛 Bug Report

It works fine for a few days , after few days it is not working. When I supply a co-ordinates to look up into the placemark of that place, It throws an exception "PlatformException(IO_ERROR, A network error occurred trying to lookup the supplied coordinates " . But , the same co-ordinate's placemark was returned correctly at the beginning, after few days of using it , it shows this error. 

### Configuration

**Version:** 1.0.5

**Platform:** 
 Android

**Comment by mvanbeusekom** [comment] 2021-03-08 08:22
Duplicate of #9 and #23. Please have a look there for detailed information.

**Closed by mvanbeusekom** 2021-03-08 08:22 UTC
