### ISSUE TITLE
locationFromAddress doesn't recognize 90210 postal code

### ISSUE THREAD

**Issue by NickalasB** [Baseflow/flutter-geocoding#114] opened 2022-10-25 20:15 UTC
## 🐛 Bug Report

Calling `locationFromAddress` with a Beverly Hills postal code (90210) throws a `NoResultFoundException`

### Expected behavior
Calling `locationFromAddress('90210')` should return proper lat/long coordinates from Beverly Hills, California.

### Reproduction steps

Below is a code sample but just call `GeocodingPlatform.instance.locationFromAddress('90210')` and the exception will be thrown.

This was discovered because I use 90210 a lot as a test postal code because it's easy to remember... thanks to growing up in the 90s 😆 

<details>
<summary>Basic code sample</summary>
<br>

```
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Geo Coding Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  Future<void> _incrementCounter() async {
  // This is just to showcase that this particular postal code throws an error
    try {
     final beverlyHillsCoordinates = await GeocodingPlatform.instance.locationFromAddress('90210');
    print('Beverly Hills Coordinates = $beverlyHillsCoordinates')
    } catch (e) {
      print('error $e');
    }

    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => _incrementCounter(),
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), //
    );
  }
}

```

</details>

### Configuration

**Version:** 1.x
`^9.0.2`

**Platform:** 
- [ X] :iphone: iOS
- [ X] :robot: Android

**Comment by TimHoogstrate** [comment] 2023-11-02 12:58
Dear @NickalasB,

I've tested this and I can reproduce it. The plugin uses the Geocoder api. And if you enter the test zipcode in the [geocoding response overview] (https://developers.google.com/maps/documentation/geocoding/overview#GeocodingResponses) it also does not return a result. There seems to be more zipcodes that have this behaviour. Like e.g. `12539`. the zipcode `90210` seems to work when you add `us ` as a prefix. So maybe there is just too little information to determine a proper locations. It does not look like there is an issue in our plugin, so I'll close this issue for now.

Kind regards,

**Closed by TimHoogstrate** 2023-11-02 12:58 UTC
Labels: type: bug, P2
