### ISSUE TITLE
PlacemarkFromCoordinated throwing PlatformException(IO_ERROR, A network error occurred trying to lookup the supplied coordinates

### ISSUE THREAD

**Issue by Flokart** [Baseflow/flutter-geocoding#85] opened 2022-02-03 10:09 UTC
Full Error: PlatformException(IO_ERROR, A network error occurred trying to lookup the supplied coordinates (latitude: 24.808313, longitude: 46.602053)., null, null)

Upon further tests I found out that if I call placemarkFromCoordinates using my location as the geopoint it works perfectly fine but when using any other location it doesn't.

**Comment by mvanbeusekom** [comment] 2022-03-09 09:01
This issue is  caused by the rate limitations related to the free services provided by Android (see README and also issues #9, #12, #23, #28, 35# and #49).

I will be closing this issue now as there is nothing I can do about this error. You are simply hitting the limitations of the free services provided by Google and Apple.

**Closed by mvanbeusekom** 2022-03-09 09:01 UTC

**Comment by MuhammadRahman2** [comment] 2022-09-25 11:45
the same was also accur me in emulator. when was i install in physical device problem was sloved.
