### ISSUE TITLE
PlatformException(IO_ERROR, A network error occurred trying to lookup the supplied coordinates (latitude: 24.808313, longitude: 46.602053)., null, null)

### ISSUE THREAD

**Issue by mohammednabil95** [Baseflow/flutter-geocoding#83] opened 2022-01-31 10:02 UTC
I am getting an error "PlatformException(IO_ERROR, A network error occurred trying to lookup the supplied coordinates (latitude: 24.808313, longitude: 46.602053)., null, null)" whenever I try to convert latitude and longitude to address.
Before it was working fine but since last 7 days I'm facing this issue. (Note: Only facing this issue in android physical device)

I TRIED

Change wifi and also mobile data
Restarted my android physical device (Huawei Nova 3)
Updated the latest version (currently using geocoding: ^2.0.2)

**Comment by Flokart** [comment] 2022-02-03 09:13
I'm getting the same error as well, I tried adding breakpoints and apparently when going step by step and slowing down it works as it should. Maybe there's something going on with ongoing Flutter operations that are blocking this method from executing. Nevertheless, if we could get an update on this issue by the creator of the package would be great.

**Comment by Flokart** [comment] 2022-02-03 09:16
I actually thought it was the breakpoint fixing it, but apparently it was only working the first time I called it (not because of the breakpoint) and every time after that it's failing.

**Comment by mvanbeusekom** [comment] 2022-03-09 09:02
This issue is  caused by the rate limitations related to the free services provided by Android (see README and also issues #9, #12, #23, #28, 35# and #49).

I will be closing this issue now as there is nothing I can do about this error. You are simply hitting the limitations of the free services provided by Google and Apple.

**Closed by mvanbeusekom** 2022-03-09 09:02 UTC
