### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by ABDALLAH-MPIANA** [Baseflow/flutter-geocoding#137] opened 2023-03-20 17:57 UTC
Note: C:\Users\xx\AppData\Local\Pub\Cache\hosted\pub.dev\geocoding_android-2.1.0\android\src\main\java\com\baseflow\geocoding\Geocoding.java uses or overrides a deprecated API.

**Comment by mvanbeusekom** [comment] 2023-07-13 07:49
duplicate of #109

**Closed by mvanbeusekom** 2023-07-13 07:49 UTC
