### ISSUE TITLE
The plugin `geocoder` uses a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by Bilonik** [Baseflow/flutter-geocoding#62] opened 2021-08-05 14:13 UTC
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by bilalhammoud** [comment] 2021-09-14 13:19
After updating to Flutter 2.5.0 I'm getting this error every time I run `flutter pub get`

```
The plugin `geocoder` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
```

I have the newest version of geocoder:
`geocoder: ^0.2.1`

**Comment by Bilonik** [comment] 2021-09-15 14:46
@bilalhammoud , yes after upgrading to 2.5.0 the error started to show.

**Comment by hussamDana92** [comment] 2021-09-16 05:59
I have the same issue, after upgrading version flutter to 2.5.0

**Comment by MiguelAlvesMiguel** [comment] 2021-09-19 11:10
Same issue here 2.5.1

**Comment by mathulan** [comment] 2021-09-23 19:17
Same issue in 2.5.1
The plugin `geocoder` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by Shveetsov** [comment] 2021-09-25 09:45
Та же проблема

**Comment by nikolas8** [comment] 2021-09-30 09:30
Same issue in 2.5.1
geocoder: ^0.2.1
The plugin geocoder uses a deprecated version of the Android embedding......

Any news on how to fix this issue?

**Comment by bilalhammoud** [comment] 2021-09-30 09:41
Apparently this package is not maintained anymore, therefore I switched to [geocode](geocode) package which has same functionality & it is null safety.

**Comment by nikolas8** [comment] 2021-09-30 10:03
> Apparently this package is not maintained anymore, therefore I switched to [geocode](https://pub.dev/packages/geocode) package which has same functionality & it is null safety.

Thanks for the reply! Will use that one as well then!

**Comment by JDDV** [comment] 2021-09-30 13:58
> Apparently this package is not maintained anymore, therefore I switched to [geocode](https://pub.dev/packages/geocode) package which has same functionality & it is null safety.

This package is still maintained and taken care off. We are very busy with lots of different plugins and try to do our best to keep things up to date.

That being said, I still can not reproduce the issue. @bilalhammoud, @nikolas8, @mathulan, you all said you use version `^0.2.1` of the geocoder plugin. As stated in the `CHANGELOG` we migrated to null safety in version `2.0.0` (newest version is ^2.0.1) and it's migrated to the 'new' Android V2 API. Can you all please try to update to the newest version of the plugin, and see if it solved the problem?

Please let me know if it worked, so we can fix this if the issue still exists. Thanks in advance

**Comment by nikolas8** [comment] 2021-10-01 09:43
> > Apparently this package is not maintained anymore, therefore I switched to [geocode](https://pub.dev/packages/geocode) package which has same functionality & it is null safety.
> 
> This package is still maintained and taken care off. We are very busy with lots of different plugins and try to do our best to keep things up to date.
> 
> That being said, I still can not reproduce the issue. @bilalhammoud, @nikolas8, @mathulan, you all said you use version `^0.2.1` of the geocoder plugin. As stated in the `CHANGELOG` we migrated to null safety in version `2.0.0` (newest version is ^2.0.1) and it's migrated to the 'new' Android V2 API. Can you all please try to update to the newest version of the plugin, and see if it solved the problem?
> 
> Please let me know if it worked, so we can fix this if the issue still exists. Thanks in advance

Even when i try to get the package from git using:
  geocoder:
    git:
      url: git://github.com/aloisdeniel/flutter_geocoder
i still get the same error:

_The plugin `geocoder` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs._

**Comment by aiyub007** [comment] 2021-10-01 14:31
same issue 2.5.0

**Comment by arafat1971** [comment] 2021-10-03 15:16
Same issue here ...

The plugin `geocoder` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
Process finished with exit code 0

**Comment by SylvesterTube** [comment] 2021-10-03 17:17
What's the solution ?

**Comment by yahi99** [comment] 2021-10-09 17:35
Pleas any update ????

**Comment by XeBastian** [comment] 2021-10-19 20:32
Has anyone already found the workaround of this? 
I am facing the very same issue flutter 2.5.1

**Comment by aliazimoshan** [comment] 2021-11-06 18:02
I am facing the same issue in flutter 2.5.1

**Comment by coding2solve** [comment] 2021-11-09 04:13
Facing the same error. I tried to use this version geocorder - 2.0.0 I ran into this error. 

Because project depends on geocoder ^2.0.0 which doesn't match any versions, version solving failed.
pub get failed (1; Because ferrahub depends on geocoder ^2.0.0 which doesn't match any versions, version solving failed.)
Process finished with exit code 1

**Comment by Asquare17** [comment] 2022-01-02 10:20
@JDDV Mot people are confusng package [geocoding](https://pub.dev/packages/geocoding) from baseflow with [geocoder](https://pub.dev/packages/geocoder) from Alois Daniel. This error is actually for the geocoder package and it is not actively maintained again. You can close this issue.

**Comment by JDDV** [comment] 2022-01-06 08:57
@Asquare17, It looks like you're right, thank you for bringing it to our attention. 
Most of the people here are talking about **geocoder** and not this plugin from Baseflow called **geocoding**.
I will close this issue for now. Feel free to open up a new issue if there are still questions

**Closed by JDDV** 2022-01-06 08:57 UTC
Labels: platform: android, status: waiting for customer response

**Comment by MansoorShopini** [comment] 2022-01-18 12:47
> > > Apparently this package is not maintained anymore, therefore I switched to [geocode](https://pub.dev/packages/geocode) package which has same functionality & it is null safety.
> > 
> > 
> > This package is still maintained and taken care off. We are very busy with lots of different plugins and try to do our best to keep things up to date.
> > That being said, I still can not reproduce the issue. @bilalhammoud, @nikolas8, @mathulan, you all said you use version `^0.2.1` of the geocoder plugin. As stated in the `CHANGELOG` we migrated to null safety in version `2.0.0` (newest version is ^2.0.1) and it's migrated to the 'new' Android V2 API. Can you all please try to update to the newest version of the plugin, and see if it solved the problem?
> > Please let me know if it worked, so we can fix this if the issue still exists. Thanks in advance
> 
> Even when i try to get the package from git using: geocoder: git: url: git://github.com/aloisdeniel/flutter_geocoder i still get the same error:
> 
> _The plugin `geocoder` uses a deprecated version of the Android embedding. To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs._

Thank You for your answer and I have a question that how we can find deprecated Packages from our project?
