### ISSUE TITLE
Flutter 3.3.0 Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\geocoding-2.0.5\android\src\main\java\com\baseflow\geocoding\Geocoding.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by mohamedsalah414** [Baseflow/flutter-geocoding#105] opened 2022-08-31 08:29 UTC
### **Flutter 3.3.0**
```
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\geocoding-2.0.5\android\src\main\java\com\baseflow\geocoding\Geocoding.java uses or overrides a deprecated API.
```

**Comment by Isuru-Nanayakkara** [comment] 2023-06-11 07:33
I wonder if there's a specific reason why this hasn't been addressed since apparently this ticket has been open for almost 1 year now. I'm on v2.1.0 and still see this warning.

**Comment by mvanbeusekom** [comment] 2023-07-13 07:58
Duplicate of #109, we are tracking progress there.

**Closed by mvanbeusekom** 2023-07-13 07:58 UTC
