### ISSUE TITLE
placemarkFromCoordinates() not working

### ISSUE THREAD

**Issue by mshamsi502** [Baseflow/flutter-geocoding#57] opened 2021-06-12 12:06 UTC
## 🐛 Bug Report

i try use placemarkFromCoordinates() but i get bellow error:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(IO_ERROR, A network error occurred trying to lookup the supplied coordinates (latitude: 25.697771, longitude: 78.654394)., null, null)
E/flutter ( 5364): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:597
E/flutter ( 5364): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:158
E/flutter ( 5364): <asynchronous suspension>
E/flutter ( 5364): #2      MethodChannelGeocoding.placemarkFromCoordinates
package:geocoding_platform_interface/…/implementations/method_channel_geocoding.dart:56
E/flutter ( 5364): <asynchronous suspension>
E/flutter ( 5364): #3      _SingleAddressDetailWidgetState.build.<anonymous closure>.<anonymous closure>
package:jeanswest/…/userAddresses/single-address-detail-widget.dart:390
E/flutter ( 5364): <asynchronous suspension>
E/flutter ( 5364):
```

I use geocoding: ^2.0.0 plugin and check other older versions like 1.0.5

my code:

```
388    LatLng newLatLng = LatLng(25.697771, 78.654394);
390    List<Placemark> dbAddress =
391       await placemarkFromCoordinates(
392          newLatLng.latitude,
393          newLatLng.longitude,
394        );
```

**Version:** 2.0.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by C4s4r** [comment] 2021-06-13 11:33
I encounter the same problem since yesterday **when testing on my real device**. Before it was working fine.
```
PlatformException(NOT_FOUND, No address information found for supplied coordinates (latitude: 51,53, longitude: 7,26)., null, null)
```
(Lat & Lng shortened for privacy reasons)

However, **on an android emulator it works as expected**.

**Comment by mshamsi502** [comment] 2021-06-13 11:40
@C4s4r I test on the android emulator and my real device android phone! but both showing this error 😕.
please inform me if u get a reason or solution, tancks

**Comment by C4s4r** [comment] 2021-06-13 12:22
@mshamsi502 It also seems like your error message is different, but with the same result.

This problem worries me since I have a released app that is build on this API call, which now doesn't work due to this address resolving fail.

Looks like an API problem to me... Hopefully this can be solved as fast as possible.

**Comment by C4s4r** [comment] 2021-06-14 09:19
After the confirmation of a friend that it works fine on his device, I restarted my phone it works again.
I have no Idea why, but I guess it was just my phone because it also worked on my emulator.

Still don't know why I encountered this behaviour on my phone...

**Comment by hasimam** [comment] 2021-06-20 19:18
I get the same issue, and it goes away after restarting my phone (OnePlus 7 pro), it seems to be random. Any suggested more reliable alternative way o get placeMark from lat/long?

**Comment by andre-paraense** [comment] 2021-07-15 10:19
I am experiencing the same error as well, only on Android, using `geocoding: 2.0.0`. Weird thing is it happens both on emulator and real device, but sometimes it works randomly, likewise said before as well.

I/flutter ( 4502): PlatformException(IO_ERROR, A network error occurred trying to lookup the supplied coordinates (latitude: -23.583747, longitude: -46.678073)., null, null)

**Comment by C4s4r** [comment] 2021-07-15 10:23
Has someone with an device that has these problems already checked, if this can be reproduced with the native Google geoparsing service that his package uses?
Because than it would not be related to the _flutter-geocoding_ package.

**Comment by maah75** [comment] 2021-07-20 13:33
I also had the same issue and I fixed it by rebooting my phone. my phone also (OnePlus 7 pro)

**Comment by jagritjkh** [comment] 2021-07-23 09:24
I am also experiencing the same error as well, geocoding versions 2.0.0.

**Comment by phjl** [comment] 2021-07-25 18:43
> I get the same issue, and it goes away after restarting my phone (OnePlus 7 pro), it seems to be random. Any suggested more reliable alternative way o get placeMark from lat/long?

Rebooting worked on my (OnePlus 7 pro) as well but after the first reload the exceptions are back.

**Comment by mvanbeusekom** [comment] 2021-08-20 19:19
This issue is  caused by the rate limitations related to the free services provided by Android (see README and also issues #9, #12, #23, #28, 35# and #49).

I will be closing this issue now as there is nothing I can do about this error. You are simply hitting the limitations of the free services provided by Google and Apple.

**Closed by mvanbeusekom** 2021-08-20 19:19 UTC

**Comment by Nikzed** [comment] 2023-06-10 18:22
Still having same issue on my Emulators 2 years from original post

**Comment by gitshubhsss** [comment] 2025-03-26 16:12
am using  List<Placemark> placemarks = await placemarkFromCoordinates(
      data.latitude!,
      data.latitude!,
    );

to fetch the address am form pune but it is printing something like this 

   Name: Borkou Yala, 
I/flutter ( 4775):       Street: Borkou Yala, 
I/flutter ( 4775):       ISO Country Code: TD,
I/flutter ( 4775):       Country: Chad,
I/flutter ( 4775):       Postal code: ,
I/flutter ( 4775):       Administrative area: Borkou,
I/flutter ( 4775):       Subadministrative area: Borkou Yala,
I/flutter ( 4775):       Locality: ,
I/flutter ( 4775):       Sublocality: ,
I/flutter ( 4775):       Thoroughfare: ,
I/flutter ( 4775):       Subthoroughfare:
